### ISSUE TITLE
Also block PlayStore install and update

### ISSUE THREAD

**Issue by FredJul** [dbrodie/AdBuster#3]
I wanted to use that app to filter my ads but also noticed that unfortunately it also block the download of app or update from PlayStore (infinite loader). I can install a app right away after switching off the vpn.

Everything else seems to work without hassle.

Android 7.0

**Comment by julian-klode** [comment]
@FredJul It's a bug in Android 7. DownloadManager and other code hardcoding a connection does not work with partial VPN connections (if you route all traffic through the VPN, it works fine...). In julian-klode/dns66 - which is basically a fork of AdBuster's core logic with a nice UI, host files, and some more features (but without an auto updater, except for F-Droid) - I worked around it by whitelisting the play store (and adding an app whitelist screen).

**Comment by FredJul** [comment]
@julian-klode , thanks for the explanation. I'll install dns66 right away and test that, thanks for the information :)
